// Pokopia House Planner — Pokémon data
// Each Pokémon includes its National Dex number (used for sprites),
// name, primary type, and preferred habitat type used in Pokopia.
//
// Habitat types: Bright | Dark | Dry | Humid | Warm | Cool

const HABITATS = {
  BRIGHT: 'Bright',
  DARK:   'Dark',
  DRY:    'Dry',
  HUMID:  'Humid',
  WARM:   'Warm',
  COOL:   'Cool',
};

const HABITAT_META = {
  Bright: { emoji: '☀️', label: 'Bright',  desc: 'Sunny meadows, flower gardens, open grasslands' },
  Dark:   { emoji: '🌑', label: 'Dark',    desc: 'Caves, haunted ruins, shadowy thickets' },
  Dry:    { emoji: '🏜️', label: 'Dry',     desc: 'Desert oases, boulder fields, arid plains' },
  Humid:  { emoji: '💧', label: 'Humid',   desc: 'Ponds, rivers, wetlands, hydrated flower beds' },
  Warm:   { emoji: '🔥', label: 'Warm',    desc: 'Campsites, volcanic vents, hot springs' },
  Cool:   { emoji: '❄️', label: 'Cool',    desc: 'Snowfields, frozen hollows, icy groves' },
};

// id = National Dex number (used for PokeAPI sprite URL)
const POKEMON_DATA = [
  // ── Bright ──────────────────────────────────────────────────────────
  { id:   1, name: 'Bulbasaur',   type: 'Grass',    habitat: 'Bright' },
  { id:   2, name: 'Ivysaur',     type: 'Grass',    habitat: 'Bright' },
  { id:   3, name: 'Venusaur',    type: 'Grass',    habitat: 'Bright' },
  { id:  10, name: 'Caterpie',    type: 'Bug',      habitat: 'Bright' },
  { id:  11, name: 'Metapod',     type: 'Bug',      habitat: 'Bright' },
  { id:  12, name: 'Butterfree',  type: 'Bug',      habitat: 'Bright' },
  { id:  16, name: 'Pidgey',      type: 'Normal',   habitat: 'Bright' },
  { id:  17, name: 'Pidgeotto',   type: 'Normal',   habitat: 'Bright' },
  { id:  18, name: 'Pidgeot',     type: 'Normal',   habitat: 'Bright' },
  { id:  19, name: 'Rattata',     type: 'Normal',   habitat: 'Bright' },
  { id:  20, name: 'Raticate',    type: 'Normal',   habitat: 'Bright' },
  { id:  35, name: 'Clefairy',    type: 'Fairy',    habitat: 'Bright' },
  { id:  36, name: 'Clefable',    type: 'Fairy',    habitat: 'Bright' },
  { id:  39, name: 'Jigglypuff',  type: 'Normal',   habitat: 'Bright' },
  { id:  40, name: 'Wigglytuff',  type: 'Normal',   habitat: 'Bright' },
  { id:  43, name: 'Oddish',      type: 'Grass',    habitat: 'Bright' },
  { id:  44, name: 'Gloom',       type: 'Grass',    habitat: 'Bright' },
  { id:  45, name: 'Vileplume',   type: 'Grass',    habitat: 'Bright' },
  { id:  46, name: 'Paras',       type: 'Bug',      habitat: 'Bright' },
  { id:  47, name: 'Parasect',    type: 'Bug',      habitat: 'Bright' },
  { id:  69, name: 'Bellsprout',  type: 'Grass',    habitat: 'Bright' },
  { id:  70, name: 'Weepinbell',  type: 'Grass',    habitat: 'Bright' },
  { id:  71, name: 'Victreebel',  type: 'Grass',    habitat: 'Bright' },
  { id: 102, name: 'Exeggcute',   type: 'Grass',    habitat: 'Bright' },
  { id: 103, name: 'Exeggutor',   type: 'Grass',    habitat: 'Bright' },
  { id: 113, name: 'Chansey',     type: 'Normal',   habitat: 'Bright' },
  { id: 114, name: 'Tangela',     type: 'Grass',    habitat: 'Bright' },
  { id: 133, name: 'Eevee',       type: 'Normal',   habitat: 'Bright' },
  { id: 137, name: 'Porygon',     type: 'Normal',   habitat: 'Bright' },
  { id: 152, name: 'Chikorita',   type: 'Grass',    habitat: 'Bright' },
  { id: 153, name: 'Bayleef',     type: 'Grass',    habitat: 'Bright' },
  { id: 154, name: 'Meganium',    type: 'Grass',    habitat: 'Bright' },
  { id: 161, name: 'Sentret',     type: 'Normal',   habitat: 'Bright' },
  { id: 162, name: 'Furret',      type: 'Normal',   habitat: 'Bright' },
  { id: 165, name: 'Ledyba',      type: 'Bug',      habitat: 'Bright' },
  { id: 166, name: 'Ledian',      type: 'Bug',      habitat: 'Bright' },
  { id: 183, name: 'Marill',      type: 'Water',    habitat: 'Bright' },
  { id: 184, name: 'Azumarill',   type: 'Water',    habitat: 'Bright' },
  { id: 187, name: 'Hoppip',      type: 'Grass',    habitat: 'Bright' },
  { id: 188, name: 'Skiploom',    type: 'Grass',    habitat: 'Bright' },
  { id: 189, name: 'Jumpluff',    type: 'Grass',    habitat: 'Bright' },
  { id: 191, name: 'Sunkern',     type: 'Grass',    habitat: 'Bright' },
  { id: 192, name: 'Sunflora',    type: 'Grass',    habitat: 'Bright' },
  { id: 252, name: 'Treecko',     type: 'Grass',    habitat: 'Bright' },
  { id: 253, name: 'Grovyle',     type: 'Grass',    habitat: 'Bright' },
  { id: 254, name: 'Sceptile',    type: 'Grass',    habitat: 'Bright' },
  { id: 285, name: 'Shroomish',   type: 'Grass',    habitat: 'Bright' },
  { id: 286, name: 'Breloom',     type: 'Grass',    habitat: 'Bright' },
  { id: 315, name: 'Roselia',     type: 'Grass',    habitat: 'Bright' },
  { id: 357, name: 'Tropius',     type: 'Grass',    habitat: 'Bright' },
  { id: 420, name: 'Cherubi',     type: 'Grass',    habitat: 'Bright' },
  { id: 421, name: 'Cherrim',     type: 'Grass',    habitat: 'Bright' },
  { id: 440, name: 'Happiny',     type: 'Normal',   habitat: 'Bright' },
  { id: 468, name: 'Togekiss',    type: 'Fairy',    habitat: 'Bright' },
  { id: 492, name: 'Shaymin',     type: 'Grass',    habitat: 'Bright' },

  // ── Dark ────────────────────────────────────────────────────────────
  { id:  41, name: 'Zubat',       type: 'Poison',   habitat: 'Dark' },
  { id:  42, name: 'Golbat',      type: 'Poison',   habitat: 'Dark' },
  { id:  92, name: 'Gastly',      type: 'Ghost',    habitat: 'Dark' },
  { id:  93, name: 'Haunter',     type: 'Ghost',    habitat: 'Dark' },
  { id:  94, name: 'Gengar',      type: 'Ghost',    habitat: 'Dark' },
  { id: 163, name: 'Hoothoot',    type: 'Normal',   habitat: 'Dark' },
  { id: 164, name: 'Noctowl',     type: 'Normal',   habitat: 'Dark' },
  { id: 167, name: 'Spinarak',    type: 'Bug',      habitat: 'Dark' },
  { id: 168, name: 'Ariados',     type: 'Bug',      habitat: 'Dark' },
  { id: 169, name: 'Crobat',      type: 'Poison',   habitat: 'Dark' },
  { id: 197, name: 'Umbreon',     type: 'Dark',     habitat: 'Dark' },
  { id: 198, name: 'Murkrow',     type: 'Dark',     habitat: 'Dark' },
  { id: 200, name: 'Misdreavus',  type: 'Ghost',    habitat: 'Dark' },
  { id: 215, name: 'Sneasel',     type: 'Dark',     habitat: 'Dark' },
  { id: 228, name: 'Houndour',    type: 'Dark',     habitat: 'Dark' },
  { id: 229, name: 'Houndoom',    type: 'Dark',     habitat: 'Dark' },
  { id: 261, name: 'Poochyena',   type: 'Dark',     habitat: 'Dark' },
  { id: 262, name: 'Mightyena',   type: 'Dark',     habitat: 'Dark' },
  { id: 302, name: 'Sableye',     type: 'Dark',     habitat: 'Dark' },
  { id: 353, name: 'Shuppet',     type: 'Ghost',    habitat: 'Dark' },
  { id: 354, name: 'Banette',     type: 'Ghost',    habitat: 'Dark' },
  { id: 355, name: 'Duskull',     type: 'Ghost',    habitat: 'Dark' },
  { id: 356, name: 'Dusclops',    type: 'Ghost',    habitat: 'Dark' },
  { id: 359, name: 'Absol',       type: 'Dark',     habitat: 'Dark' },
  { id: 429, name: 'Mismagius',   type: 'Ghost',    habitat: 'Dark' },
  { id: 430, name: 'Honchkrow',   type: 'Dark',     habitat: 'Dark' },
  { id: 461, name: 'Weavile',     type: 'Dark',     habitat: 'Dark' },
  { id: 477, name: 'Dusknoir',    type: 'Ghost',    habitat: 'Dark' },
  { id: 442, name: 'Spiritomb',   type: 'Ghost',    habitat: 'Dark' },

  // ── Dry ─────────────────────────────────────────────────────────────
  { id:  27, name: 'Sandshrew',   type: 'Ground',   habitat: 'Dry' },
  { id:  28, name: 'Sandslash',   type: 'Ground',   habitat: 'Dry' },
  { id:  50, name: 'Diglett',     type: 'Ground',   habitat: 'Dry' },
  { id:  51, name: 'Dugtrio',     type: 'Ground',   habitat: 'Dry' },
  { id:  74, name: 'Geodude',     type: 'Rock',     habitat: 'Dry' },
  { id:  75, name: 'Graveler',    type: 'Rock',     habitat: 'Dry' },
  { id:  76, name: 'Golem',       type: 'Rock',     habitat: 'Dry' },
  { id:  95, name: 'Onix',        type: 'Rock',     habitat: 'Dry' },
  { id: 111, name: 'Rhyhorn',     type: 'Ground',   habitat: 'Dry' },
  { id: 112, name: 'Rhydon',      type: 'Ground',   habitat: 'Dry' },
  { id: 207, name: 'Gligar',      type: 'Ground',   habitat: 'Dry' },
  { id: 208, name: 'Steelix',     type: 'Steel',    habitat: 'Dry' },
  { id: 218, name: 'Slugma',      type: 'Fire',     habitat: 'Dry' },
  { id: 219, name: 'Magcargo',    type: 'Fire',     habitat: 'Dry' },
  { id: 231, name: 'Phanpy',      type: 'Ground',   habitat: 'Dry' },
  { id: 232, name: 'Donphan',     type: 'Ground',   habitat: 'Dry' },
  { id: 246, name: 'Larvitar',    type: 'Rock',     habitat: 'Dry' },
  { id: 247, name: 'Pupitar',     type: 'Rock',     habitat: 'Dry' },
  { id: 248, name: 'Tyranitar',   type: 'Rock',     habitat: 'Dry' },
  { id: 299, name: 'Nosepass',    type: 'Rock',     habitat: 'Dry' },
  { id: 304, name: 'Aron',        type: 'Steel',    habitat: 'Dry' },
  { id: 305, name: 'Lairon',      type: 'Steel',    habitat: 'Dry' },
  { id: 306, name: 'Aggron',      type: 'Steel',    habitat: 'Dry' },
  { id: 322, name: 'Numel',       type: 'Fire',     habitat: 'Dry' },
  { id: 323, name: 'Camerupt',    type: 'Fire',     habitat: 'Dry' },
  { id: 328, name: 'Trapinch',    type: 'Ground',   habitat: 'Dry' },
  { id: 329, name: 'Vibrava',     type: 'Ground',   habitat: 'Dry' },
  { id: 330, name: 'Flygon',      type: 'Ground',   habitat: 'Dry' },
  { id: 331, name: 'Cacnea',      type: 'Grass',    habitat: 'Dry' },
  { id: 332, name: 'Cacturne',    type: 'Grass',    habitat: 'Dry' },
  { id: 449, name: 'Hippopotas',  type: 'Ground',   habitat: 'Dry' },
  { id: 450, name: 'Hippowdon',   type: 'Ground',   habitat: 'Dry' },
  { id: 464, name: 'Rhyperior',   type: 'Ground',   habitat: 'Dry' },
  { id: 472, name: 'Gliscor',     type: 'Ground',   habitat: 'Dry' },
  { id: 476, name: 'Probopass',   type: 'Rock',     habitat: 'Dry' },

  // ── Humid ───────────────────────────────────────────────────────────
  { id:   7, name: 'Squirtle',    type: 'Water',    habitat: 'Humid' },
  { id:   8, name: 'Wartortle',   type: 'Water',    habitat: 'Humid' },
  { id:   9, name: 'Blastoise',   type: 'Water',    habitat: 'Humid' },
  { id:  54, name: 'Psyduck',     type: 'Water',    habitat: 'Humid' },
  { id:  55, name: 'Golduck',     type: 'Water',    habitat: 'Humid' },
  { id:  60, name: 'Poliwag',     type: 'Water',    habitat: 'Humid' },
  { id:  61, name: 'Poliwhirl',   type: 'Water',    habitat: 'Humid' },
  { id:  62, name: 'Poliwrath',   type: 'Water',    habitat: 'Humid' },
  { id:  72, name: 'Tentacool',   type: 'Water',    habitat: 'Humid' },
  { id:  73, name: 'Tentacruel',  type: 'Water',    habitat: 'Humid' },
  { id:  79, name: 'Slowpoke',    type: 'Water',    habitat: 'Humid' },
  { id:  80, name: 'Slowbro',     type: 'Water',    habitat: 'Humid' },
  { id:  86, name: 'Seel',        type: 'Water',    habitat: 'Humid' },
  { id: 116, name: 'Horsea',      type: 'Water',    habitat: 'Humid' },
  { id: 117, name: 'Seadra',      type: 'Water',    habitat: 'Humid' },
  { id: 118, name: 'Goldeen',     type: 'Water',    habitat: 'Humid' },
  { id: 119, name: 'Seaking',     type: 'Water',    habitat: 'Humid' },
  { id: 120, name: 'Staryu',      type: 'Water',    habitat: 'Humid' },
  { id: 121, name: 'Starmie',     type: 'Water',    habitat: 'Humid' },
  { id: 129, name: 'Magikarp',    type: 'Water',    habitat: 'Humid' },
  { id: 130, name: 'Gyarados',    type: 'Water',    habitat: 'Humid' },
  { id: 134, name: 'Vaporeon',    type: 'Water',    habitat: 'Humid' },
  { id: 158, name: 'Totodile',    type: 'Water',    habitat: 'Humid' },
  { id: 159, name: 'Croconaw',    type: 'Water',    habitat: 'Humid' },
  { id: 160, name: 'Feraligatr',  type: 'Water',    habitat: 'Humid' },
  { id: 170, name: 'Chinchou',    type: 'Water',    habitat: 'Humid' },
  { id: 171, name: 'Lanturn',     type: 'Water',    habitat: 'Humid' },
  { id: 186, name: 'Politoed',    type: 'Water',    habitat: 'Humid' },
  { id: 194, name: 'Wooper',      type: 'Water',    habitat: 'Humid' },
  { id: 195, name: 'Quagsire',    type: 'Water',    habitat: 'Humid' },
  { id: 230, name: 'Kingdra',     type: 'Water',    habitat: 'Humid' },
  { id: 258, name: 'Mudkip',      type: 'Water',    habitat: 'Humid' },
  { id: 259, name: 'Marshtomp',   type: 'Water',    habitat: 'Humid' },
  { id: 260, name: 'Swampert',    type: 'Water',    habitat: 'Humid' },
  { id: 270, name: 'Lotad',       type: 'Water',    habitat: 'Humid' },
  { id: 271, name: 'Lombre',      type: 'Water',    habitat: 'Humid' },
  { id: 272, name: 'Ludicolo',    type: 'Water',    habitat: 'Humid' },
  { id: 278, name: 'Wingull',     type: 'Water',    habitat: 'Humid' },
  { id: 279, name: 'Pelipper',    type: 'Water',    habitat: 'Humid' },
  { id: 283, name: 'Surskit',     type: 'Bug',      habitat: 'Humid' },
  { id: 284, name: 'Masquerain',  type: 'Bug',      habitat: 'Humid' },
  { id: 298, name: 'Azurill',     type: 'Normal',   habitat: 'Humid' },
  { id: 318, name: 'Carvanha',    type: 'Water',    habitat: 'Humid' },
  { id: 319, name: 'Sharpedo',    type: 'Water',    habitat: 'Humid' },
  { id: 320, name: 'Wailmer',     type: 'Water',    habitat: 'Humid' },
  { id: 321, name: 'Wailord',     type: 'Water',    habitat: 'Humid' },
  { id: 349, name: 'Feebas',      type: 'Water',    habitat: 'Humid' },
  { id: 350, name: 'Milotic',     type: 'Water',    habitat: 'Humid' },
  { id: 422, name: 'Shellos',     type: 'Water',    habitat: 'Humid' },
  { id: 423, name: 'Gastrodon',   type: 'Water',    habitat: 'Humid' },
  { id: 456, name: 'Finneon',     type: 'Water',    habitat: 'Humid' },
  { id: 457, name: 'Lumineon',    type: 'Water',    habitat: 'Humid' },

  // ── Warm ────────────────────────────────────────────────────────────
  { id:   4, name: 'Charmander',  type: 'Fire',     habitat: 'Warm' },
  { id:   5, name: 'Charmeleon',  type: 'Fire',     habitat: 'Warm' },
  { id:   6, name: 'Charizard',   type: 'Fire',     habitat: 'Warm' },
  { id:  37, name: 'Vulpix',      type: 'Fire',     habitat: 'Warm' },
  { id:  38, name: 'Ninetales',   type: 'Fire',     habitat: 'Warm' },
  { id:  58, name: 'Growlithe',   type: 'Fire',     habitat: 'Warm' },
  { id:  59, name: 'Arcanine',    type: 'Fire',     habitat: 'Warm' },
  { id:  77, name: 'Ponyta',      type: 'Fire',     habitat: 'Warm' },
  { id:  78, name: 'Rapidash',    type: 'Fire',     habitat: 'Warm' },
  { id: 126, name: 'Magmar',      type: 'Fire',     habitat: 'Warm' },
  { id: 136, name: 'Flareon',     type: 'Fire',     habitat: 'Warm' },
  { id: 146, name: 'Moltres',     type: 'Fire',     habitat: 'Warm' },
  { id: 155, name: 'Cyndaquil',   type: 'Fire',     habitat: 'Warm' },
  { id: 156, name: 'Quilava',     type: 'Fire',     habitat: 'Warm' },
  { id: 157, name: 'Typhlosion',  type: 'Fire',     habitat: 'Warm' },
  { id: 240, name: 'Magby',       type: 'Fire',     habitat: 'Warm' },
  { id: 255, name: 'Torchic',     type: 'Fire',     habitat: 'Warm' },
  { id: 256, name: 'Combusken',   type: 'Fire',     habitat: 'Warm' },
  { id: 257, name: 'Blaziken',    type: 'Fire',     habitat: 'Warm' },
  { id: 390, name: 'Chimchar',    type: 'Fire',     habitat: 'Warm' },
  { id: 391, name: 'Monferno',    type: 'Fire',     habitat: 'Warm' },
  { id: 392, name: 'Infernape',   type: 'Fire',     habitat: 'Warm' },
  { id: 467, name: 'Magmortar',   type: 'Fire',     habitat: 'Warm' },

  // ── Cool ────────────────────────────────────────────────────────────
  { id:  87, name: 'Dewgong',     type: 'Water',    habitat: 'Cool' },
  { id:  91, name: 'Cloyster',    type: 'Water',    habitat: 'Cool' },
  { id: 124, name: 'Jynx',        type: 'Ice',      habitat: 'Cool' },
  { id: 131, name: 'Lapras',      type: 'Water',    habitat: 'Cool' },
  { id: 144, name: 'Articuno',    type: 'Ice',      habitat: 'Cool' },
  { id: 220, name: 'Swinub',      type: 'Ice',      habitat: 'Cool' },
  { id: 221, name: 'Piloswine',   type: 'Ice',      habitat: 'Cool' },
  { id: 225, name: 'Delibird',    type: 'Ice',      habitat: 'Cool' },
  { id: 238, name: 'Smoochum',    type: 'Ice',      habitat: 'Cool' },
  { id: 361, name: 'Snorunt',     type: 'Ice',      habitat: 'Cool' },
  { id: 362, name: 'Glalie',      type: 'Ice',      habitat: 'Cool' },
  { id: 363, name: 'Spheal',      type: 'Ice',      habitat: 'Cool' },
  { id: 364, name: 'Sealeo',      type: 'Ice',      habitat: 'Cool' },
  { id: 365, name: 'Walrein',     type: 'Ice',      habitat: 'Cool' },
  { id: 459, name: 'Snover',      type: 'Grass',    habitat: 'Cool' },
  { id: 460, name: 'Abomasnow',   type: 'Grass',    habitat: 'Cool' },
  { id: 471, name: 'Glaceon',     type: 'Ice',      habitat: 'Cool' },
  { id: 473, name: 'Mamoswine',   type: 'Ice',      habitat: 'Cool' },
  { id: 478, name: 'Froslass',    type: 'Ice',      habitat: 'Cool' },
  { id: 613, name: 'Cubchoo',     type: 'Ice',      habitat: 'Cool' },
  { id: 614, name: 'Beartic',     type: 'Ice',      habitat: 'Cool' },
  { id: 615, name: 'Cryogonal',   type: 'Ice',      habitat: 'Cool' },
];

// Deduplicate by id (some entries may repeat across habitat groups)
const POKEMON = (() => {
  const seen = new Set();
  return POKEMON_DATA.filter(p => {
    if (seen.has(p.id)) return false;
    seen.add(p.id);
    return true;
  });
})();

const MAX_HOUSE_OCCUPANTS = 4;
